---
- name: remove local users
  hosts: servera
  become: yes
  vars_files:
    - usernames.yml

  tasks:
    - name: remove default users and groups
      user:
        name: "{{ item.username }}"
        state: absent
      loop: "{{ users }}"
