---
- name: Install packages
  hosts: all
  vars_files:
    - packages.yml
  become: yes

  tasks:
    - name: add docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644

    - name: install Docker 
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: install docker-py for ansible tasks
      pip:
        name: docker-py
        state: latest
        
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true

- name: starting applications
  hosts: all
  become: yes

  tasks:
    - name: pull docker image
      docker_image:
        name: sunlnx/flask-app
        pull: yes
       
    - name: start container
      docker_container:
        name: myflask
        image: sunlnx/flask-app
        state: started
        published_ports: '5000:5000'
