---
- name: Install packages
  hosts: all
  vars_files:
    - packages.yml
  become: yes

  tasks:
    - name: add docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644

    - name: install Docker 
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
        
      
  
