---
- name: create apache folder configs
  hosts: servera
  become: yes
  vars_files:
    - storage_vars.yml

  tasks:
    - name: create physical volume
      parted:
        device: /dev/sdb
        state: present
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
      loop: "{{ partitions }}"

    - name: create volume groups
      lvg:
        vg: "{{ item.name }}"
        pvs: "{{ item.devices }}"
        state: present
      loop: "{{ volume_groups }}"

    - name: create logical volumes 
      lvol:
        vg: "{{ item.vgroup }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      loop: "{{ logical_volumes }}" 
      when: item.name not in ansible_lvm["lvs"]

    - name: create file systems
      filesystem:
       dev: "/dev/{{ item.vgroup }}/{{ item.name }}"
       fstype: xfs
      loop: "{{ logical_volumes }}"

    - name: ensure correct capacity on each lv
      lvol:
        vg: "{{ item.vgroup }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
        resizefs: yes
        force: yes
      loop: "{{ logical_volumes }}"

    - name: mount file systems
      mount:
        path: "{{ item.mount_path }}" 
        src: "/dev/{{ item.vgroup }}/{{ item.name }}"
        fstype: xfs
        state: mounted
      loop: "{{ logical_volumes }}"

