---
- name: create local users
  hosts: servera
  become: yes
  vars_files:
    - vars/users_groups.yml

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: create "{{ usergroup }}"
      group:
        name: "{{ usergroup }}" 
        state: present

    - name: create default users and groups
      user:
        name: "{{ item.username }}"
        groups: "{{ usergroup }}"
        state: present
      loop: "{{ users }}"

    - name: add users authorized_keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file','files/'+item.username+'.pub') }}"
      loop: "{{ users }}"
