---
- name: create local users
  hosts: servera
  become: yes
  vars_files:
    - users_groups.yml

  tasks:
    - name: create default users and groups
      user:
        name: "{{ item.username }}"
        groups: "{{ usergroup }}"
        state: absent
      loop: "{{ users }}"

    - name: create "{{ usergroup }}"
      group:
        name: "{{ usergroup }}" 
        state: absent
