---
- name: create local users
  hosts: servera
  become: yes
  vars_files:
    - usernames.yml

  tasks:
    - name: create default users and groups
      user:
        name: "{{ item.username }}"
        state: present
      loop: "{{ users }}"
